version: '3.8'

services:
  server:
    build:
      context: ./Server
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/tema2_database_SCD
      - PORT=5000
    networks:
      - server

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - server
      - admin-network

  mongo-express:
    image: mongo-express:latest
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=pass
    networks:
      - admin-network

networks:
  server:
    driver: bridge
  admin-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
