/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "oauth.h"
#include <stdio.h>
#include <stdlib.h>
#include <rpc/pmap_clnt.h>
#include <string.h>
#include <memory.h>
#include <sys/socket.h>
#include <netinet/in.h>
#include "server_functions.h"

#ifndef SIG_PF
#define SIG_PF void(*)(int)
#endif

static void
oauth_1(struct svc_req *rqstp, register SVCXPRT *transp)
{
	union {
		char *request_authorization_1_arg;
		requestTokenAcces request_authorization_token_1_arg;
		validateDelegatedAction validate_delegated_action_1_arg;
		char *approve_request_token_1_arg;
		char *get_acces_token_and_handel_ttl_1_arg;
	} argument;
	char *result;
	xdrproc_t _xdr_argument, _xdr_result;
	char *(*local)(char *, struct svc_req *);

	switch (rqstp->rq_proc) {
	case NULLPROC:
		(void) svc_sendreply (transp, (xdrproc_t) xdr_void, (char *)NULL);
		return;

	case REQUEST_AUTHORIZATION:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) request_authorization_1_svc;
		break;

	case REQUEST_AUTHORIZATION_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_requestTokenAcces;
		_xdr_result = (xdrproc_t) xdr_returnRequestTokenAcces;
		local = (char *(*)(char *, struct svc_req *)) request_authorization_token_1_svc;
		break;

	case VALIDATE_DELEGATED_ACTION:
		_xdr_argument = (xdrproc_t) xdr_validateDelegatedAction;
		_xdr_result = (xdrproc_t) xdr_AuthResult;
		local = (char *(*)(char *, struct svc_req *)) validate_delegated_action_1_svc;
		break;

	case APPROVE_REQUEST_TOKEN:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_wrapstring;
		local = (char *(*)(char *, struct svc_req *)) approve_request_token_1_svc;
		break;

	case GET_ACCES_TOKEN_AND_HANDEL_TTL:
		_xdr_argument = (xdrproc_t) xdr_wrapstring;
		_xdr_result = (xdrproc_t) xdr_gatAndHandelTtl;
		local = (char *(*)(char *, struct svc_req *)) get_acces_token_and_handel_ttl_1_svc;
		break;

	case INCREASE_COUNT:
		_xdr_argument = (xdrproc_t) xdr_void;
		_xdr_result = (xdrproc_t) xdr_int;
		local = (char *(*)(char *, struct svc_req *)) increase_count_1_svc;
		break;

	default:
		svcerr_noproc (transp);
		return;
	}
	memset ((char *)&argument, 0, sizeof (argument));
	if (!svc_getargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		svcerr_decode (transp);
		return;
	}
	result = (*local)((char *)&argument, rqstp);
	if (result != NULL && !svc_sendreply(transp, (xdrproc_t) _xdr_result, result)) {
		svcerr_systemerr (transp);
	}
	if (!svc_freeargs (transp, (xdrproc_t) _xdr_argument, (caddr_t) &argument)) {
		fprintf (stderr, "%s", "unable to free arguments");
		exit (1);
	}
	return;
}

int
main (int argc, char **argv)
{
	register SVCXPRT *transp;

	pmap_unset (OAUTH, OAUTH_V1);

	transp = svcudp_create(RPC_ANYSOCK);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create udp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH, OAUTH_V1, oauth_1, IPPROTO_UDP)) {
		fprintf (stderr, "%s", "unable to register (OAUTH, OAUTH_V1, udp).");
		exit(1);
	}

	transp = svctcp_create(RPC_ANYSOCK, 0, 0);
	if (transp == NULL) {
		fprintf (stderr, "%s", "cannot create tcp service.");
		exit(1);
	}
	if (!svc_register(transp, OAUTH, OAUTH_V1, oauth_1, IPPROTO_TCP)) {
		fprintf (stderr, "%s", "unable to register (OAUTH, OAUTH_V1, tcp).");
		exit(1);
	}

	char *usr_file, *res_file, *apr_file;

	usr_file = argv[1];
	res_file = argv[2];
	apr_file = argv[3];
	TTL = atoi(argv[4]);

	Counter_Resources_Taken = 0;

	// facem rost de continutul fisierului approvals
	approve_file = fopen(apr_file, "r");

	if (!approve_file) {
        printf("Err for approve file.\n");
		fflush(stdout);
        return 1;
    }

	char line[250];
	int capacity = 10;
	int count = 0;

	// drepturile vor fi retinute intr-un vector de liste
	approvals_list = malloc(capacity * sizeof(resoureces_list_t *));

	while(fgets(line, sizeof(line), approve_file) != NULL) {

		char *simple_line = strtok(line, "\n");
		char *token = strtok(simple_line, ",");

		char resName[100];
		char op[5];
		resoureces_list_t *list = init_list_res();

		while (token != NULL) {
			strcpy(resName, token);
			token = strtok(NULL, ",");

			if (token != NULL) {
				strcpy(op, token);
			}

			insert_node_res(list, resName, op);

			token = strtok(NULL, ",");
		}

		if (count == capacity) {
			approvals_list = resize_array(approvals_list, &capacity);
		}

		approvals_list[count] = list;

		count++;
	}

	fclose(approve_file);

	// facem rost de resurse din fisier
	FILE *resources_file = fopen(res_file, "r");

	if (!resources_file) {
        printf("Err for resources file.\n");
		fflush(stdout);
        return 1;
    }

    fscanf(resources_file, "%d", &nr_resources);

	// vor fi retinute intr-un vector de stringuri
	resources = (char **)malloc(nr_resources*sizeof(char *));

	char res[100];
	for (int i=0; i<nr_resources; i++) {
		fscanf(resources_file, "%s", &res);

		resources[i] = (char *)malloc((strlen(res) + 1) * sizeof(char));
		strcpy(resources[i], res);
	}

	fclose(resources_file);

	// facem rost de useri
	FILE *users_file;

	users_file = fopen(usr_file, "r");

	if (!users_file) {
        printf("Err for users file.\n");
		fflush(stdout);
        return 1;
    }

	// initializam lista de structuri de useri
	users_main_list = init_list();

	int clients;
    fscanf(users_file, "%d", &clients);

	char user[15];
	for (int i=0; i<clients; i++) {
		fscanf(users_file, "%s", &user);

		insert_node(users_main_list, user, "");
	}

	fclose(users_file);

	svc_run ();
	
	// eliberam resursele folosite
	destroy_list(users_main_list);

	// free resources
	for (int i = 0; i < nr_resources; i++) {
        free(resources[i]);
    }
    free(resources);

	// free approvels 
	for (int i = 0; i < count; i++) {
		destroy_list_res(approvals_list[i]);
	}
	free(approvals_list);

	fprintf (stderr, "%s", "svc_run returned");
	exit (1);
	/* NOTREACHED */
}