version: '3.9'

services:
  mqtt_broker:
    image: eclipse-mosquitto:2.0.11
    ports:
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
      - scd3_mosquitto_data:/mosquitto/data
      - scd3_mosquitto_logs:/mosquitto/log
    networks:
      - mqtt_network

  influxdb:
    image: influxdb:latest
    ports:
      - "8086:8086"
    volumes:
      - scd3_influxdb_data:/var/lib/influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_RETENTION=0
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=cris
      - DOCKER_INFLUXDB_INIT_PASSWORD=cris1234
      - DOCKER_INFLUXDB_INIT_ORG=my-org
      - DOCKER_INFLUXDB_INIT_BUCKET=iot_data
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=cris1234
    networks:
      - data_network

  mqtt_adaptor:
    image: scd3/mqtt_adaptor:latest
    environment:
      - INFLUX_TOKEN=cris1234
      - INFLUX_ORG=my-org
      - INFLUX_BUCKET=iot_data
      - DEBUG_DATA_FLOW=true
    networks:
      - mqtt_network
      - data_network

  grafana:
    image: grafana/grafana:latest
    ports:
      - "80:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=asistent
      - GF_SECURITY_ADMIN_PASSWORD=grafanaSCD2024
    depends_on:
      - influxdb
    volumes:
      - scd3_grafana_data:/var/lib/grafana
    networks:
      - data_network

networks:
  mqtt_network:
    driver: overlay
  data_network:
    driver: overlay

volumes:
  scd3_mosquitto_data:
  scd3_mosquitto_logs:
  scd3_influxdb_data:
    external: true
  scd3_grafana_data:
    external: true

