version: '3.8'
services:
  mosquitto:
    image: eclipse-mosquitto
    container_name: mosquitto-broker
    ports:
      - "1883:1883"
    volumes:
      - ./config/mosquitto.conf:/mosquitto/config/mosquitto.conf
